name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:

jobs:
  build:
    name: Build and Deploy
    runs-on: fuadzqnr

    env:
      APP_NAME: fleurs-noir
      IMAGE_NAME: fleurs-noir
      REGISTRY: docker.io
      DEV_SERVER: root@103.178.153.102
      PROD_SERVER: root@103.178.153.102
      DOCKER_CONTEXT: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Node Install & Package
        run: |
            npm install
            npm run build

      - name: Build Image
        run: |
          docker login echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build -t ${{ env.APP_NAME }}:$GITHUB_SHA $DOCKER_CONTEXT
          docker push ${{ env.APP_NAME }}:$GITHUB_SHA

      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        run: |
          ssh $DEV_SERVER "
            docker pull ${{ env.APP_NAME }}:$GITHUB_SHA &&
            docker stop ${{ env.APP_NAME }} || true &&
            docker rm ${{ env.APP_NAME }} || true &&
            docker run -d --name ${{ env.APP_NAME }} -p 3000:3000 ${{ env.APP_NAME }}:$GITHUB_SHA
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_DEV }}
