name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:

jobs:
  build:
    name: Build and Deploy
    runs-on: fuadzqnr

    env:
      APP_NAME: fleurs-noir
      IMAGE_NAME: fleurs-noir
      REGISTRY: docker.io
      SSH_SERVER: 103.178.153.102
      SSH_USER: root
      DOCKER_CONTEXT: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:$GITHUB_SHA

      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $SSH_SERVER
          username: $SSH_USER
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            docker pull ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:$GITHUB_SHA &&
            docker stop ${{ env.APP_NAME }} || true &&
            docker rm ${{ env.APP_NAME }} || true &&
            docker run -d --name ${{ env.APP_NAME }} -p 3000:3000 ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:$GITHUB_SHA
